/**
 * Maps the owned squat score (numbers only) into the app's `AnalysisResult`
 * presentation/storage model.
 *
 * Pure + deterministic: the coaching strings here are templated from the
 * measured numbers, NOT generated by an LLM. This is the Phase-1 placeholder —
 * item 3 swaps in Gemini phrasing behind these exact fields (summary /
 * topStrength / topImprovement / per-metric feedback) without touching the
 * scoring or the result model.
 */

import { getScoreTier } from "@/constants/theme"
import type { AnalysisResult, MetricScore } from "@/constants/types"
import type { SquatScore } from "@/lib/scoring/squat"

// Phrasing thresholds (degrees) — describe a measurement in plain language.
// Distinct from the scoring thresholds in squat.ts; these only pick words.
const PARALLEL_DEG = 90
const NEAR_PARALLEL_DEG = 110
const TALL_TORSO_DEG = 30
const MODERATE_TORSO_DEG = 50

const REFILM_NOTE =
  " Some joints were hard to track — refilm side-on with your full body in frame for a more reliable score."

export interface BuildSquatResultOptions {
  readonly exerciseId: string
  readonly exerciseName: string
  /** Caller supplies these so the mapper stays deterministic for tests. */
  readonly id: string
  readonly timestamp: number
}

function describeDepth(kneeAngle: number): string {
  const deg = Math.round(kneeAngle)
  if (kneeAngle <= PARALLEL_DEG) {
    return `Knee bent to ${deg}° at the bottom — at or below parallel.`
  }
  if (kneeAngle <= NEAR_PARALLEL_DEG) {
    return `Knee bent to ${deg}° at the bottom — just above parallel.`
  }
  return `Knee bent to ${deg}° at the bottom — well above parallel.`
}

function describeTorso(torsoLean: number): string {
  const deg = Math.round(torsoLean)
  if (torsoLean <= TALL_TORSO_DEG) {
    return `Torso leaned ${deg}° from vertical — tall and controlled.`
  }
  if (torsoLean <= MODERATE_TORSO_DEG) {
    return `Torso leaned ${deg}° from vertical — a moderate forward lean.`
  }
  return `Torso leaned ${deg}° from vertical — a large forward lean.`
}

function strengthLine(score: SquatScore): string {
  if (score.depth >= score.torso) {
    return `Strong squat depth — ${Math.round(score.bottomKneeAngle)}° of knee flexion at the bottom.`
  }
  return `Good torso control — only ${Math.round(score.bottomTorsoLean)}° of forward lean at the bottom.`
}

function improvementLine(score: SquatScore): string {
  // Coach the weaker dimension (ties → coach depth).
  if (score.depth <= score.torso) {
    return `Sit deeper. You reached ${Math.round(score.bottomKneeAngle)}° of knee bend; aim to get your hips below parallel (~90° or less).`
  }
  return `Stay taller. Your torso leaned ${Math.round(score.bottomTorsoLean)}°; brace your core and keep your chest up to reduce forward lean.`
}

export function buildSquatResult(
  score: SquatScore,
  opts: BuildSquatResultOptions,
): AnalysisResult {
  const metrics: MetricScore[] = [
    {
      metricId: "depth",
      name: "Depth",
      score: score.depth,
      feedback: describeDepth(score.bottomKneeAngle),
    },
    {
      metricId: "torso",
      name: "Torso Control",
      score: score.torso,
      feedback: describeTorso(score.bottomTorsoLean),
    },
  ]

  const summary =
    `${opts.exerciseName}: ${score.total}/100. Depth ${score.depth}, torso control ${score.torso}.` +
    (score.lowConfidence ? REFILM_NOTE : "")

  return {
    id: opts.id,
    exerciseId: opts.exerciseId,
    exerciseName: opts.exerciseName,
    overallScore: score.total,
    metrics,
    summary,
    topStrength: strengthLine(score),
    topImprovement: improvementLine(score),
    timestamp: opts.timestamp,
    tier: getScoreTier(score.total).label as AnalysisResult["tier"],
    lowConfidence: score.lowConfidence,
  }
}
